"""
setup.py — Family Recipe Agent generator
Reads family-profile.yaml and generates:
  - CLAUDE.md
  - .claude/skills/{skill_id}.md (one per family member)
  - web/family-data.js
"""
import sys
import os
import json

try:
    import yaml
except ImportError:
    print("PyYAML not installed. Run: pip install pyyaml")
    sys.exit(1)


def load_profile(path="family-profile.yaml"):
    if not os.path.exists(path):
        print(f"Error: {path} not found.")
        print("Copy family-profile.example.yaml to family-profile.yaml and fill it in.")
        sys.exit(1)
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def generate_claude_md(profile):
    cuisines = ", ".join(profile["cuisines"])
    members_lines = "\n".join(
        f"- **{m['name']}**{' (' + m['location'] + ')' if m.get('location') else ''}: "
        f"{', '.join(m['specialties'])}. {m['style']}"
        for m in profile["members"]
    )
    skills_lines = "\n".join(
        f"- `/{m['skill_id']}` — {m['name']}: {m.get('signature_dish', m['specialties'][0])}"
        for m in profile["members"]
    )
    return f"""# {profile["family_name"]} — Claude Code Context

## Family Overview
**Cuisines:** {cuisines}

## Family Members
{members_lines}

## Available Skills
{skills_lines}

## Working with This Project
- Edit `family-profile.yaml` to add or update family members
- Run `python setup.py` to regenerate all files
- Add exported chat conversations to `conversations/` for additional context
- Open `web/index.html` to use the family-facing app
"""


def generate_skill(member, cuisines):
    cuisine_str = ", ".join(cuisines)
    specialties_str = ", ".join(member["specialties"])
    signature = member.get("signature_dish", member["specialties"][0])
    location_line = f"**Location:** {member['location']}\n" if member.get("location") else ""
    story_line = f"\n**Background:** {member['story']}" if member.get("story") else ""
    tips_section = "\n## Her Tips\n" + "\n".join(f"- {t}" for t in member["tips"]) if member.get("tips") else ""
    avoid_section = "\n## What She Never Does\n" + "\n".join(f"- {a}" for a in member["avoid"]) if member.get("avoid") else ""
    substitutions_section = "\n## Her Substitutions\n" + "\n".join(f"- {s}" for s in member["substitutions"]) if member.get("substitutions") else ""
    corrections_section = "\n## What AI Gets Wrong About Her Cooking\n" + "\n".join(f"- {c}" for c in member["corrections"]) if member.get("corrections") else ""
    return f"""# {member["name"]}'s Kitchen

You are a recipe assistant trained on {member["name"]}'s kitchen.

**Cuisine:** {cuisine_str}
{location_line}**Specialties:** {specialties_str}
**Cooking style:** {member["style"]}
**Signature dish:** {signature}{story_line}{tips_section}{avoid_section}{substitutions_section}{corrections_section}

## Your Job

The user will describe a dish from memory — an ingredient, a texture, an occasion, a smell.
Reconstruct the full recipe from that description.

Always provide:
1. Ingredients with quantities
2. Step-by-step method
3. What to pair it with
4. One tip specific to {member["name"]}'s style

If the description is vague, make reasonable assumptions based on {cuisine_str} tradition.
State your assumptions clearly at the top.

End every response with: "Does this sound right? Tell me what to adjust."
"""


def generate_family_data_js(profile):
    members_json = json.dumps(profile["members"], indent=2, ensure_ascii=False)
    cuisines_json = json.dumps(profile["cuisines"])
    return f"""// Auto-generated by setup.py — do not edit directly.
// Edit family-profile.yaml and re-run: python setup.py

const FAMILY_DATA = {{
  familyName: {json.dumps(profile["family_name"])},
  cuisines: {cuisines_json},
  members: {members_json}
}};
"""


def main():
    profile = load_profile()
    family_name = profile["family_name"]
    members = profile["members"]

    # CLAUDE.md
    with open("CLAUDE.md", "w", encoding="utf-8") as f:
        f.write(generate_claude_md(profile))
    print("Generated CLAUDE.md")

    # Skills
    os.makedirs(".claude/skills", exist_ok=True)
    for member in members:
        skill_path = f".claude/skills/{member['skill_id']}.md"
        with open(skill_path, "w", encoding="utf-8") as f:
            f.write(generate_skill(member, profile["cuisines"]))
        print(f"Generated {skill_path}")

    # family-data.js
    os.makedirs("web", exist_ok=True)
    with open("web/family-data.js", "w", encoding="utf-8") as f:
        f.write(generate_family_data_js(profile))
    print("Generated web/family-data.js")

    print(f"\nDone. {len(members)} family members configured for {family_name}.")
    print("Next steps:")
    print("  1. Copy web/config.example.js to web/config.js")
    print("  2. Add your Claude API key to web/config.js")
    print("  3. Open web/index.html in a browser")


if __name__ == "__main__":
    main()
